# docker-compose.yml
version: '3.9'
services:
  database:
    image: "mysql"
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'url_shortener'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test_pass'
      MYSQL_ROOT_PASSWORD: 'root'
  check-db-started: 
    image: jwilder/dockerize:0.6.1
    depends_on:
      - database
    command: 'dockerize -wait=tcp://db:3306'